### ISSUE TITLE
Support for hmatrix 0.17

### ISSUE THREAD

**Issue by nh2** [basvandijk/levmar#7]
With hmatrix 0.17 the compilation fails; one reason is because of deprecated modules being removed there (they just moved to the main hmatrix module, that's easy to fix); the other one is that one can no longer do

```haskell
deriving instance (Eq r, Container Vector r) => Eq (Constraints r)
```

it has to be

```haskell
deriving instance (Eq r, Container Vector r, Num r) => Eq (Constraints r)
```

now (wants a `Num` constraint). Does it make sense to add this constraint to this instance?

**Comment by basvandijk** [comment]
Thanks for the heads-up. This should now be fixed in [1.2.1.6](http://hackage.haskell.org/package/levmar-1.2.1.6).
